Replace generic ProgramErrors with program-specific WalletErrors
StrikeProtocols/strike-solana-wallet pull request #30
Opened 2022-02-15 14:21 UTC by dgabriele

- Replaced ProgramErrors with program-specific WalletErrors to make the cause of errors clearer.
- Added docstrings to WalletErrors, based on the format found in Solana Program Library. For example: https://github.com/solana-labs/solana-program-library/blob/master/token/program/src/error.rs
- Small refactoring in Makefile to make it more DRY.

## How Has This Been Tested?
Tests updated to catch new error codes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix breaking (fix that would cause existing functionality to change)

2022-02-15 16:58 UTC, bholzman commented on src/model/wallet.rs
> +            return Err(WalletError::InvalidSlot.into());
So yeah, thinking that `InvalidSlot` might be too generic given how many times it occurs. The debug messages make it clear what the problem actually was to a developer, but as there doesn't seem to be a way to retrieve the logs when using the `solana-program-test` framework, checking this error code in a unit test might suffer from the original problem you were trying to fix (of a test getting the error it expects but for the wrong reason).

This one could be maybe something like `SlotAlreadyOccupied`, and the next one could be more like `UnknownSigner`, etc.

2022-02-15 18:08 UTC, dgabriele commented on src/model/wallet.rs
> +            return Err(WalletError::InvalidSlot.into());
Sounds good :)

2022-02-15 19:37 UTC, bflood-strike commented on src/model/wallet.rs
>          if self.approval_timeout_for_config.as_secs() == 0 {
shouldn't this be checking it's within the range 1 minute -> max

2022-02-16 15:49 UTC, bflood-strike commented on src/model/wallet.rs
>          if self.approval_timeout_for_config.as_secs() == 0 {
I'm talking about this line (265) that is checking the approval_timeout_for config 
` if self.approval_timeout_for_config.as_secs() == 0 {`

2022-02-17 14:20 UTC, bholzman requested changes

2022-02-17 14:20 UTC, bholzman commented on src/error.rs
> +    WhitelistingStatusOff,
this should be the `WhitelistDisabled` above, not a new error

2022-02-17 14:20 UTC, bholzman commented on src/model/wallet.rs
> +            return Err(WalletError::InvalidSlot.into());
seems like there are still a lot of `InvalidSlot` errors, I thought you said you were going to change them, particularly where a single instruction is returning the same `InvalidSlot` error for different conditions, which was what you set out to fix here

2022-02-17 17:39 UTC, dgabriele commented on src/error.rs
> +    WhitelistingStatusOff,
I got it. Fixed everything up now.

2022-02-17 17:46 UTC, bholzman requested changes
Just one more change then I think good to go

2022-02-17 21:14 UTC, bholzman approved these changes
🚢

2022-02-17 21:18 UTC, bholzman approved these changes

2022-02-17 21:19 UTC, merged